[package]
name = "system_monitor"
version = "0.2.0"
authors = ["George Hosu <george@cerebralab.com>"]

[dependencies]
agent_lib = {path="../../agent_lib"}
serde_json = "1.0"
sysinfo = "0.5.1"
serde_derive = "1.0"
serde = "1.0"