[package]
name = "inquisitor_agent_system_monitor"
version = "0.3.0"
authors = ["George Hosu <george@cerebralab.com>"]

[dependencies]
inquisitor_lib = {path="../../../inquisitor_lib"}
serde_json = "1.0.16"
sysinfo = "0.5.5"
serde_derive = "1.0.43"
serde = "1.0.43"
